version: '3.8'
services:
  app:
    build: .
    container_name: task
    networks:
      - app-network
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8080:8080"

  db:
    image: postgres:16.2-alpine
    container_name: postgres
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-rc-alpine
    container_name: redis
    networks:
      - app-network
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

volumes:
  db-data:
  cache:


networks:
  app-network: