spring:
  datasource:
    url: jdbc:mysql://db:5432/task
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


#  sql:
#    init:
#      mode: always
#      continue-on-error: false
#      data-locations: classpath:initdb.sql

security:
  jwt:
    secret: ZmdoZmpoZ2dqa2hHRkRGR0Q1NjdWRkNDY2ZjZmdoYmZ4ZHhjdmJmZHRydEZEWEZERENGR2ZjZmZjZnZibmdmNmJoeXRq
    access: 3600000
    refresh: 2592000000

